import json

data = {
  'http://www.daft.ie/cork/houses-for-sale/ballineen/main-street-ballineen-cork-1792868/': {
    'beds': 3,
    'property_title': 'Main Street, Ballineen, Co. Cork',
    'price': 110000,
    'no_of_photos': 9,
    'latitude': 51.735691,
    'facility': ['Parking', 'Oil Fired Central Heating'],
    'selling_type': 'private-treaty',
    'bathrooms': 1,
    'seller_id': 52,
    'published_date': '2018-07-06',
    'page_name': 'PropertyDetails',
    'ber_classification': 'B3',
    'property_category': 'sale',
    'surface': 167.2,
    'ad_id': '11792868',
    'property_type': 'terraced',
    'seller_type': 'agent',
    'longitude': -8.951411,
    'area': 'Ballineen',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Lehanes & Associates Estate Agents Ltd',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/glasheen/4-st-josephs-terrace-gould-street-cork-glasheen-cork-1764834/': {
    'beds': 5,
    'property_title': "4 St Joseph\\\\'s Terrace, Gould Street, Cork, Glasheen, Co. Cork",
    'price': 270000,
    'no_of_photos': 9,
    'latitude': 51.890279,
    'facility': ['Gas Fired Central Heating'],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 2490,
    'published_date': '2018-07-06',
    'page_name': 'PropertyDetails',
    'ber_classification': 'C2',
    'property_category': 'sale',
    'surface': 157.1,
    'ad_id': '11764834',
    'property_type': 'terraced',
    'seller_type': 'agent',
    'longitude': -8.481763,
    'area': 'Glasheen',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Frank V Murphy & Co.',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/dunderrow/lahern-dunderrow-cork-1792848/': {
    'beds': 4,
    'property_title': 'Lahern, Dunderrow, Co. Cork',
    'price': 450000,
    'no_of_photos': 60,
    'latitude': 51.732816,
    'facility': [''],
    'selling_type': 'private-treaty',
    'bathrooms': 2,
    'seller_id': 3548,
    'published_date': '2018-07-09',
    'page_name': 'PropertyDetails',
    'ber_classification': 'D2',
    'property_category': 'sale',
    'surface': 151.0,
    'ad_id': '11792848',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.619583,
    'area': 'Dunderrow',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Keane Mahony Smith',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/cork-city/10-the-grove-orchard-road-cork-city-cork-1706474/': {
    'beds': 4,
    'property_title': '10 The Grove, Orchard Road, Cork City, Co. Cork',
    'price': 595000,
    'no_of_photos': 11,
    'latitude': 51.891826,
    'facility': [''],
    'selling_type': 'private-treaty',
    'bathrooms': 2,
    'seller_id': 2490,
    'published_date': '2018-07-06',
    'page_name': 'PropertyDetails',
    'ber_classification': 'B3',
    'property_category': 'sale',
    'surface': 131.0,
    'ad_id': '11706474',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.504524,
    'area': 'Cork City',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Frank V Murphy & Co.',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/ballyvolane/12-north-avenue-lios-rua-ballyvolane-cork-1793909/': {
    'beds': 4,
    'property_title': '12 North Avenue, Lios Rua, Ballyvolane, Co. Cork',
    'price': 290000,
    'no_of_photos': 47,
    'latitude': 51.917305,
    'facility': [''],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 4124,
    'published_date': '2018-07-07',
    'page_name': 'PropertyDetails',
    'ber_classification': 'B3',
    'property_category': 'sale',
    'surface': 125.0,
    'ad_id': '11793909',
    'property_type': 'semi-detached',
    'seller_type': 'agent',
    'longitude': -8.440433,
    'area': 'Ballyvolane',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'DNG Murphy Condon',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/midleton/ballycroneen-midleton-cork-1789790/': {
    'beds': 3,
    'property_title': 'Ballycroneen, Midleton, Co. Cork',
    'price': 600000,
    'no_of_photos': 19,
    'latitude': 51.811236,
    'facility': [''],
    'selling_type': 'private-treaty',
    'bathrooms': 2,
    'seller_id': 4205,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'C3',
    'property_category': 'sale',
    'surface': 155.0,
    'ad_id': '11789790',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.112374,
    'area': 'Midleton',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Home & Away Real Estate Ltd',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/glanmire/48-old-avenue-glanmire-cork-1734448/': {
    'beds': 4,
    'property_title': '48. Old Avenue, Glanmire, Co. Cork',
    'price': 330000,
    'no_of_photos': 62,
    'latitude': 51.931012,
    'facility': ['Parking', 'Gas Fired Central Heating', 'Alarm'],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 9274,
    'published_date': '2018-07-06',
    'page_name': 'PropertyDetails',
    'ber_classification': 'C2',
    'property_category': 'sale',
    'surface': 157.1,
    'ad_id': '11734448',
    'property_type': 'semi-detached',
    'seller_type': 'agent',
    'longitude': -8.388333,
    'area': 'Glanmire',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Joe Organ Auctioneers',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/rochestown/12-the-ovals-rochestown-cork-1686648/': {
    'beds': 5,
    'property_title': '12 The Ovals, Rochestown, Co. Cork',
    'price': 685000,
    'no_of_photos': 20,
    'latitude': 51.874394,
    'facility': ['Parking', 'Gas Fired Central Heating'],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 2490,
    'published_date': '2018-07-06',
    'page_name': 'PropertyDetails',
    'ber_classification': 'C3',
    'property_category': 'sale',
    'surface': 223.0,
    'ad_id': '11686648',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.410176,
    'area': 'Rochestown',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Frank V Murphy & Co.',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/waterfall/cluain-mhuire-corbally-waterfall-cork-1780613/': {
    'beds': 4,
    'property_title': 'Cluain Mhuire, Corbally, Waterfall, Co. Cork',
    'price': 385000,
    'no_of_photos': 17,
    'latitude': 51.846728,
    'facility': ['Parking', 'Oil Fired Central Heating'],
    'selling_type': 'private-treaty',
    'bathrooms': 1,
    'seller_id': 2490,
    'published_date': '2018-07-06',
    'page_name': 'PropertyDetails',
    'ber_classification': 'B3',
    'property_category': 'sale',
    'surface': 134.7,
    'ad_id': '11780613',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.58254,
    'area': 'Waterfall',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Frank V Murphy & Co.',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/midleton/kielty-rocky-road-midleton-cork-1790045/': {
    'beds': 4,
    'property_title': 'Kielty, Rocky Road, Midleton, Co. Cork',
    'price': 385000,
    'no_of_photos': 29,
    'latitude': 51.90664,
    'facility': ['Parking', 'Alarm', 'Oil Fired Central Heating'],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 1957,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'E1',
    'property_category': 'sale',
    'surface': 174.2,
    'ad_id': '11790045',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.156727,
    'area': 'Midleton',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Cronin Wall Properties',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/bandon/the-gables-mishells-bandon-cork-1797530/': {
    'beds': 5,
    'property_title': 'The Gables, Mishells, Bandon, Co. Cork',
    'price': 375000,
    'no_of_photos': 37,
    'latitude': 51.766307,
    'facility': ['Gas Fired Central Heating', 'Alarm'],
    'selling_type': 'private-treaty',
    'bathrooms': 4,
    'seller_id': 1228,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'C2',
    'property_category': 'sale',
    'surface': 210.0,
    'ad_id': '11797530',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.759783,
    'area': 'Bandon',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Paddy Murray Auctioneers',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/bandon/rockhouse-bridge-kilmacsimon-bandon-cork-1794026/': {
    'beds': 3,
    'property_title': 'Rockhouse Bridge, Kilmacsimon, Bandon, Co. Cork',
    'price': 455000,
    'no_of_photos': 34,
    'latitude': 51.732715,
    'facility': [''],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 1228,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'C1',
    'property_category': 'sale',
    'surface': 220.0,
    'ad_id': '11794026',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.639147,
    'area': 'Bandon',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Paddy Murray Auctioneers',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/macroom/drum-carra-south-kilbarry-macroom-cork-1791416/': {
    'beds': 5,
    'property_title': 'Dromcarra South, Kilbarry,, Macroom, Co. Cork',
    'price': 325000,
    'no_of_photos': 20,
    'latitude': 51.858698,
    'facility': [''],
    'selling_type': 'private-treaty',
    'bathrooms': 4,
    'seller_id': 2556,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'B3',
    'property_category': 'sale',
    'surface': 231.0,
    'ad_id': '11791416',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -9.025068,
    'area': 'Macroom',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Irish & European',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/mallow/16-kingsfort-avenue-castlepark-village-mallow-cork-1792860/': {
    'beds': 4,
    'property_title': '16 Kingsfort Avenue, Castlepark Village, Mallow, Co. Cork',
    'price': 260000,
    'no_of_photos': 15,
    'latitude': 52.138474,
    'facility': ['Parking', 'Gas Fired Central Heating', 'Alarm'],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 5479,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'B3',
    'property_category': 'sale',
    'surface': 167.2,
    'ad_id': '11792860',
    'property_type': 'semi-detached',
    'seller_type': 'agent',
    'longitude': -8.630281,
    'area': 'Mallow',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Peter Barry Property Consultants, Auctioneers & Valuers',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/ballinhassig/gleann-orga-ballinhassig-cork-1775757/': {
    'beds': 4,
    'property_title': 'Gleann Orga, Ballinhassig, Co. Cork',
    'price': 319000,
    'no_of_photos': 3,
    'latitude': 51.810567768326,
    'facility': ['Parking', 'Gas Fired Central Heating', 'Alarm', 'Wired for Cable Television', 'Wheelchair Access'],
    'selling_type': 'private-treaty',
    'bathrooms': 3,
    'seller_id': 3548,
    'published_date': '2018-07-09',
    'page_name': 'PropertyDetails',
    'ber_classification': 'D2',
    'property_category': 'sale',
    'surface': 151.0,
    'ad_id': '11775757',
    'property_type': 'semi-detached',
    'seller_type': 'agent',
    'longitude': -8.5366327923213,
    'area': 'Ballinhassig',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Keane Mahony Smith',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/bandon/coolanagh-newcestown-bandon-cork-1792596/': {
    'beds': 3,
    'property_title': 'Coolanagh, Newcestown, Bandon, Co. Cork',
    'price': 299000,
    'no_of_photos': 37,
    'latitude': 51.744654131475,
    'facility': ['Alarm', 'Wheelchair Access', 'Oil Fired Central Heating'],
    'selling_type': 'private-treaty',
    'bathrooms': 2,
    'seller_id': 1228,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'B3',
    'property_category': 'sale',
    'surface': 180.0,
    'ad_id': '11792596',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.7396338013206,
    'area': 'Bandon',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Paddy Murray Auctioneers',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/kinsale/swilcan-lodge-compass-hill-kinsale-cork-1695387/': {
    'beds': 5,
    'property_title': 'Swilcan Lodge, Compass Hill, Kinsale, Co. Cork',
    'price': 1200000,
    'no_of_photos': 38,
    'latitude': 51.696517,
    'facility': ['Parking', 'Oil Fired Central Heating'],
    'selling_type': 'private-treaty',
    'bathrooms': 4,
    'seller_id': 15,
    'published_date': '2018-07-09',
    'page_name': 'PropertyDetails',
    'ber_classification': 'D2',
    'property_category': 'sale',
    'surface': 165.0,
    'ad_id': '11695387',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.525652,
    'area': 'Kinsale',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'James Murphy & Co. Auctioneers & Valuers',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/midleton/no3-river-street-cloyne-midleton-cork-1793046/': {
    'beds': 2,
    'property_title': 'No.3 River Street, Cloyne, Midleton, Co. Cork',
    'price': 125000,
    'no_of_photos': 16,
    'latitude': 51.8644272421,
    'facility': [''],
    'selling_type': 'private-treaty',
    'bathrooms': 1,
    'seller_id': 1957,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'E2',
    'property_category': 'sale',
    'surface': 69.7,
    'ad_id': '11793046',
    'property_type': 'terraced',
    'seller_type': 'agent',
    'longitude': -8.1221408024162,
    'area': 'Midleton',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Cronin Wall Properties',
    'open_viewing': 'no'
  },
  'http://www.daft.ie/cork/houses-for-sale/kinsale/kinure-oysterhaven-kinsale-cork-1706487/': {
    'beds': 5,
    'property_title': 'Kinure, Oysterhaven, Kinsale, Co. Cork',
    'price': 450000,
    'no_of_photos': 24,
    'latitude': 51.692175,
    'facility': ['Parking', 'Gas Fired Central Heating', 'Alarm'],
    'selling_type': 'private-treaty',
    'bathrooms': 2,
    'seller_id': 2898,
    'published_date': '2018-07-10',
    'page_name': 'PropertyDetails',
    'ber_classification': 'C3',
    'property_category': 'sale',
    'surface': 155.0,
    'ad_id': '11706487',
    'property_type': 'detached',
    'seller_type': 'agent',
    'longitude': -8.439809,
    'area': 'Kinsale',
    'price_type': '',
    'county': 'Cork',
    'seller_name': 'Engel & Voelkers',
    'open_viewing': 'no'
  }
}


with open('data/sampledata.json', 'w') as fout:
    json.dump(data, fout, sort_keys=True,indent=4, separators=(',', ': '))
    
